{% set name = "cvat-cli" %}
{% set version = "2.29.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cvat_cli-{{ version }}.tar.gz
  sha256: 50464643742eb2b2533d296ed5701b99ec4ae840e4952d4c35680306b8e15b47

build:
  entry_points:
    - cvat-cli=cvat_cli.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - cvat-sdk =={{ version }}

test:
  imports:
    - cvat_cli
  commands:
    - pip check
    - cvat-cli --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.cvat.ai/
  summary: Command-line client for CVAT
  doc_url: https://docs.cvat.ai/docs/api_sdk/cli/
  dev_url: https://github.com/cvat-ai/cvat
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - achimgaedke
