schema_version: 1

context:
  name: cvat-cli
  version: "2.43.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/cvat_cli-${{ version }}.tar.gz
  sha256: 17c954dcae3ebdacdecbc9c4dd435d61d5327e8bb13e7584dbdc628fc49b8286

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - cvat-cli=cvat_cli.__main__:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - cvat-sdk ==${{ version }}

tests:
  - python:
      imports:
        - cvat_cli
  - requirements:
      run:
        - pip
        - python ${{ python_min }}
    script:
      - pip check
      - cvat-cli --help

about:
  summary: Command-line client for CVAT
  license: MIT
  license_file: LICENSE
  homepage: https://www.cvat.ai/
  repository: https://github.com/cvat-ai/cvat
  documentation: https://docs.cvat.ai/docs/api_sdk/cli/

extra:
  recipe-maintainers:
    - achimgaedke
